name: CI - Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # === BACKEND ===
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backend jar
        working-directory: Backend
        run: ./gradlew clean bootJar

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gestion-pedidos-backend:${{ github.sha }}

      # === FRONTEND ===
      - name: Build frontend
        working-directory: Frontend
        run: |
          npm ci
          npm run build

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gestion-pedidos-frontend:${{ github.sha }}
